export const ISSUE_TAG = Object.freeze({
  APP_ISSUE:     'APP_ISSUE',
  CHARGER_ISSUE: 'CHARGER_ISSUE',
  PAYMENT_ISSUE: 'PAYMENT_ISSUE',
  RFID_ISSUE:    'RFID_ISSUE',
  SESSION_ISSUE: 'SESSION_ISSUE',
  OCPI_SYNC:     'OCPI_SYNC',
})
