name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/cz.ops.backend

            git pull origin main

            npm install

            pm2 restart chargezone-backend || pm2 start npm --name chargezone-backend -- start

            pm2 save

            pm2 flush
